import styles from "./page.module.css";

export const metadata = {
  title: "Methodology",
  description:
    "How SCOTUS Predictor generates AI-assisted Supreme Court predictions using primary legal sources, voting data, and a multi-step analytical pipeline.",
};

export default function MethodologyPage() {
  return (
    <article className={styles.page}>
      <header className={styles.header}>
        <h1 className={styles.title} style={{ fontFamily: "var(--font-serif)" }}>
          Methodology
        </h1>
        <p className={styles.subtitle}>
          How predictions are generated from primary legal sources.
        </p>
      </header>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>How This Works</h2>
        <p>
          Each prediction is generated by a multi-step analytical pipeline using
          Claude (Anthropic&rsquo;s AI) with extensive primary legal source material.
          The pipeline processes Supreme Court opinions cited in party briefs,
          oral argument transcripts, selected amicus briefs, and statistical
          voting data from the Supreme Court Database.
        </p>
        <p>
          Each justice is analyzed individually with their own relevant prior
          writings, then results are synthesized into coherent outcome scenarios
          with probability estimates.
        </p>
        <p>
          The system uses primary legal sources &mdash; actual opinions, actual
          transcripts, actual briefs &mdash; not media coverage, punditry, or
          secondary analysis.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Pipeline Steps</h2>
        <ol className={styles.stepList}>
          <li>
            Automated extraction of cited cases from party and selected amicus
            briefs
          </li>
          <li>
            Download and summarization of cited opinions, preserving doctrinal
            holdings and vote breakdowns
          </li>
          <li>
            Integration of SCDB statistical voting data for the current natural
            court and relevant issue areas
          </li>
          <li>
            Issue analysis: identifying the doctrinal questions that will
            determine the outcome
          </li>
          <li>
            Per-justice vote prediction (9 separate API calls, each with
            justice-specific prior writings and full case context)
          </li>
          <li>
            Scenario construction: synthesizing 9 predictions into coherent
            outcome paths with probabilities
          </li>
          <li>
            Opinion drafting: generating majority, concurrence, and dissent texts
            in authentic judicial voice
          </li>
        </ol>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Data Sources</h2>
        <ul className={styles.sourceList}>
          <li>
            <strong>Supreme Court Database (SCDB)</strong> &mdash; Washington
            University
          </li>
          <li>
            <strong>CourtListener</strong> &mdash; Free Law Project
          </li>
          <li>
            <strong>Supreme Court official filings</strong> &mdash;
            supremecourt.gov
          </li>
          <li>
            <strong>Oral argument transcripts</strong> &mdash; supremecourt.gov /
            Oyez
          </li>
          <li>
            <strong>Full opinion texts</strong> for all cases cited in party
            briefs
          </li>
        </ul>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Limitations</h2>
        <p>
          These predictions are AI-generated analytical models, not certainties.
          The Supreme Court regularly surprises observers. Key limitations include:
        </p>
        <ul className={styles.sourceList}>
          <li>
            AI models may miss subtle dynamics not captured in text (personal
            relationships, behind-the-scenes negotiations)
          </li>
          <li>
            Oral argument signals are imperfect predictors &mdash; justices
            sometimes play devil&rsquo;s advocate
          </li>
          <li>
            Historical voting patterns may not predict behavior on novel
            constitutional questions
          </li>
          <li>
            Citations should be independently verified; the system flags
            uncertain references
          </li>
        </ul>
      </section>
    </article>
  );
}
